//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANIMAUX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class animal
    {
        public int passport_number { get; set; }
        public string category { get; set; }
        public string name { get; set; }
        public System.DateTime birth_date { get; set; }
        public string breed { get; set; }
        public string sex { get; set; }
    }
}
