//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANIMAUX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cards
    {
        public int id { get; set; }
        public int organisation_id { get; set; }
        public int district_id { get; set; }
        public int animal_id { get; set; }
        public System.DateTime date_added { get; set; }
    
        public virtual animals animals { get; set; }
        public virtual districts districts { get; set; }
        public virtual organisations organisations { get; set; }
    }
}
