//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANIMAUX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class publication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public publication()
        {
            this.photos_by_pubs = new HashSet<photos_by_pubs>();
        }
    
        public int id { get; set; }
        public System.DateTime added_date { get; set; }
        public string main_photo { get; set; }
        public string city { get; set; }
        public int animal_id { get; set; }
        public string type { get; set; }
    
        public virtual animal animal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<photos_by_pubs> photos_by_pubs { get; set; }
    }
}
