//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANIMAUX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class publications
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public publications()
        {
            this.photos_by_pubs = new HashSet<photos_by_pubs>();
        }
    
        public int id { get; set; }
        public System.DateTime added_date { get; set; }
        public string photo { get; set; }
        public string city { get; set; }
        public int animal_id { get; set; }
        public string type { get; set; }
    
        public virtual animals animals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<photos_by_pubs> photos_by_pubs { get; set; }
    }
}
