//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANIMAUX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public int user_role { get; set; }
        public int user_organistaion { get; set; }
        public int user_district { get; set; }
    
        public virtual districts districts { get; set; }
        public virtual organisations organisations { get; set; }
        public virtual roles roles { get; set; }
    }
}
