//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANIMAUX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public Nullable<int> user_role { get; set; }
        public Nullable<int> user_organistaion { get; set; }
        public Nullable<int> user_district { get; set; }
    
        public virtual district district { get; set; }
        public virtual organisation organisation { get; set; }
        public virtual role role { get; set; }
    }
}
